CREATE TABLE sessions (
  session_id SERIAL PRIMARY KEY,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  begin_dttm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end_dttm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
)