CREATE TABLE IF NOT EXISTS payments (
  payment_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
  payment_sum DOUBLE,
  payment_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);