CREATE TABLE If NOT EXISTS sessions (
  session_id BIGINT AUTO_INCREMENT primary key,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
  begin_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);