CREATE TABLE IF NOT EXISTS sessions(
	session_id SERIAL PRIMARY KEY,
	user_id BIGINT(20) UNSIGNED REFERENCES users(id),
	begin_dttm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	end_dttm TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
