CREATE TABLE IF NOT EXISTS sessions
(
  session_id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id),
  begin_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
